source "https://rubygems.org"
git_source(:github) { |repo| "https://github.com/#{repo}.git" }

ruby "3.2.1"

# Dotenv needs to go first
gem "dotenv-rails", groups: [:development, :test]

# Base dependencies
gem "rails", "~> 7.0.7"
gem "pg", "~> 1.1"
gem "puma", "~> 5.0"
gem "jbuilder"
gem "tzinfo-data", platforms: %i[mingw mswin x64_mingw jruby]
gem "rack-cors"
gem "temporal-ruby", github: "coinbase/temporal-ruby"

## Auth
gem "haikunator"

group :development, :test do
  gem "rubocop", require: false
  gem "standard"
  gem "pry", require: false
  gem "ruby-lsp", require: false
  gem "debug", require: false
end

group :development do
  gem "spring"
  gem "bootsnap", require: false
end
