name: Ruby

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    services:
      postgres:
        image: postgres:10.8
        env:
          POSTGRES_USER: koala_test
          POSTGRES_PASSWORD: "test"
          POSTGRES_DB: api_test
        ports:
        - 5433:5432
        # needed because the postgres container does not provide a healthcheck
        options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
        working-directory: api

    steps:
      - uses: actions/checkout@v3
      - name: Set up Ruby
        uses: ruby/setup-ruby@ec02537da5712d66d4d50a0f33b7eb52773b5ed1
        with:
          ruby-version: '3.2'
      - name: Install dependencies
        run: bundle install
      - name: Run tests
        run: bundle exec rake standard
      - name: Run Migrations
        run: RAILS_ENV=test bundle exec rails db:migrate
      - name: Run tests
        run: RAILS_ENV=test bundle exec rake test
